export type Todo = {
  id: string;
  title: string;
  completed: boolean;
  categoryId: string;
  groupId: string;
};

export const dummyTodos: Todo[] = [
  // グループ1（家族）
  { id: "1", title: "洗濯", completed: false, categoryId: "1", groupId: "1" },
  {
    id: "2",
    title: "食事の準備",
    completed: true,
    categoryId: "1",
    groupId: "1",
  },
  { id: "3", title: "掃除", completed: false, categoryId: "1", groupId: "1" },
  {
    id: "4",
    title: "買い物リスト作成",
    completed: false,
    categoryId: "2",
    groupId: "1",
  },
  {
    id: "5",
    title: "子どもの宿題確認",
    completed: true,
    categoryId: "1",
    groupId: "1",
  },
  {
    id: "6",
    title: "ご飯の買い物",
    completed: false,
    categoryId: "2",
    groupId: "1",
  },
  {
    id: "7",
    title: "トイレ掃除",
    completed: true,
    categoryId: "1",
    groupId: "1",
  },
  {
    id: "8",
    title: "家族会議",
    completed: false,
    categoryId: "4",
    groupId: "1",
  },
  {
    id: "9",
    title: "洗濯物干す",
    completed: false,
    categoryId: "1",
    groupId: "1",
  },
  {
    id: "10",
    title: "冷蔵庫チェック",
    completed: true,
    categoryId: "2",
    groupId: "1",
  },
  // グループ2（パートナー）
  {
    id: "11",
    title: "映画予約",
    completed: false,
    categoryId: "3",
    groupId: "2",
  },
  {
    id: "12",
    title: "レストラン探す",
    completed: false,
    categoryId: "3",
    groupId: "2",
  },
  {
    id: "13",
    title: "デート計画",
    completed: true,
    categoryId: "3",
    groupId: "2",
  },
  {
    id: "14",
    title: "記念日プレゼント購入",
    completed: false,
    categoryId: "2",
    groupId: "2",
  },
  {
    id: "15",
    title: "旅行下見",
    completed: false,
    categoryId: "3",
    groupId: "2",
  },
  {
    id: "16",
    title: "ホテル予約",
    completed: true,
    categoryId: "3",
    groupId: "2",
  },
  {
    id: "17",
    title: "チケット購入",
    completed: false,
    categoryId: "3",
    groupId: "2",
  },
  {
    id: "18",
    title: "スケジュール調整",
    completed: false,
    categoryId: "4",
    groupId: "2",
  },
  {
    id: "19",
    title: "クリーニング取り返す",
    completed: true,
    categoryId: "2",
    groupId: "2",
  },
  {
    id: "20",
    title: "食事予約",
    completed: false,
    categoryId: "3",
    groupId: "2",
  },
  // グループ3（友達）
  {
    id: "21",
    title: "ゲーム企画",
    completed: false,
    categoryId: "4",
    groupId: "3",
  },
  {
    id: "22",
    title: "飲み会日程調整",
    completed: true,
    categoryId: "4",
    groupId: "3",
  },
  {
    id: "23",
    title: "BBQ準備",
    completed: false,
    categoryId: "2",
    groupId: "3",
  },
  {
    id: "24",
    title: "友人に連絡",
    completed: false,
    categoryId: "4",
    groupId: "3",
  },
  {
    id: "25",
    title: "写真整理",
    completed: true,
    categoryId: "4",
    groupId: "3",
  },
  {
    id: "26",
    title: "イベント参加申込",
    completed: false,
    categoryId: "3",
    groupId: "3",
  },
  {
    id: "27",
    title: "プレゼント準備",
    completed: false,
    categoryId: "2",
    groupId: "3",
  },
  {
    id: "28",
    title: "集合場所確認",
    completed: true,
    categoryId: "4",
    groupId: "3",
  },
  {
    id: "29",
    title: "祝い金を準備",
    completed: false,
    categoryId: "2",
    groupId: "3",
  },
  {
    id: "30",
    title: "グループLINE確認",
    completed: false,
    categoryId: "4",
    groupId: "3",
  },
];
